### ISSUE TITLE
ERROR Celluloid: Punchblock::Translator::Asterisk crashed! RubyAMI::Error: RubyAMI::Error

### ISSUE THREAD

**Issue by sobanakram** [adhearsion/punchblock#261]
I am trying to setup adhearsion 2.6.4 with Asterisk 16 and when I run `ahn start` this error came up, and not able to receive call inside adhearsion although it get's connected with Asterisk,

Anyone help me out with this?

Logs:

```bundle exec ahn start .

Starting Adhearsion server at asterisk_ahn
[2020-04-27 17:36:34.074] DEBUG Adhearsion::LinuxProcName: Error while attaching libc function prctl: Function 'prctl' not found in [libc.dylib]
[2020-04-27 17:36:34.074] INFO  Adhearsion::Console: Launching Adhearsion Console
warning: setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead
AHN> 
AHN> [2020-04-27 17:36:34.074] INFO  Adhearsion::Initializer: Setting RAILS_ENV to "development"
[2020-04-27 17:36:34.133] DEBUG Punchblock::Connection::Asterisk: Starting up...
[2020-04-27 17:36:34.141] INFO  Adhearsion::PunchblockPlugin::Initializer: Starting connection to server
[2020-04-27 17:36:34.847] INFO  Adhearsion::PunchblockPlugin::Initializer: Connected to Punchblock server
[2020-04-27 17:36:34.848] INFO  Adhearsion::Process: Transitioning from booting to running with 0 active calls due to booted event.
[2020-04-27 17:36:34.848] INFO  Adhearsion::Initializer: Adhearsion v2.6.4 initialized in "development"!
[2020-04-27 17:36:35.486] ERROR Celluloid: Punchblock::Translator::Asterisk crashed!
RubyAMI::Error: RubyAMI::Error
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/responses.rb:29:in `value'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/connection/asterisk.rb:66:in `method_missing'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:209:in `send_ami_action'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:182:in `run_at_fully_booted'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:89:in `handle_ami_event'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
[2020-04-27 17:36:35.486] ERROR Adhearsion::Initializer: <RubyAMI::Error> Command output follows
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/responses.rb:29:in `value'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/connection/asterisk.rb:66:in `method_missing'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:209:in `send_ami_action'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:182:in `run_at_fully_booted'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/punchblock-2.7.5/lib/punchblock/translator/asterisk.rb:89:in `handle_ami_event'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/Users/soban/.rvm/gems/ruby-2.5.5/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'```

**Comment by bklang** [comment]
Asterisk 16 has protocol level changes that are incompatible with Adhearsion 2. I recommend you try the latest develop branch of Adhearsion, which contains improvements meant to connect to the latest Asterisk.
